/*
 * This file is generated by jOOQ.
 */
package me.tj3828.jooq.tables;


import java.util.Arrays;
import java.util.List;

import me.tj3828.jooq.Indexes;
import me.tj3828.jooq.Keys;
import me.tj3828.jooq.Public;
import me.tj3828.jooq.tables.records.MeetingRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meeting extends TableImpl<MeetingRecord> {

    private static final long serialVersionUID = -852352542;

    /**
     * The reference instance of <code>PUBLIC.MEETING</code>
     */
    public static final Meeting MEETING = new Meeting();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MeetingRecord> getRecordType() {
        return MeetingRecord.class;
    }

    /**
     * The column <code>PUBLIC.MEETING.ID</code>.
     */
    public final TableField<MeetingRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.MEETING.LOCATION</code>.
     */
    public final TableField<MeetingRecord, String> LOCATION = createField("LOCATION", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.MEETING.TITLE</code>.
     */
    public final TableField<MeetingRecord, String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.MEETING</code> table reference
     */
    public Meeting() {
        this(DSL.name("MEETING"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.MEETING</code> table reference
     */
    public Meeting(String alias) {
        this(DSL.name(alias), MEETING);
    }

    /**
     * Create an aliased <code>PUBLIC.MEETING</code> table reference
     */
    public Meeting(Name alias) {
        this(alias, MEETING);
    }

    private Meeting(Name alias, Table<MeetingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Meeting(Name alias, Table<MeetingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Meeting(Table<O> child, ForeignKey<O, MeetingRecord> key) {
        super(child, key, MEETING);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_6);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MeetingRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MeetingRecord>> getKeys() {
        return Arrays.<UniqueKey<MeetingRecord>>asList(Keys.CONSTRAINT_6);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Meeting as(String alias) {
        return new Meeting(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Meeting as(Name alias) {
        return new Meeting(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Meeting rename(String name) {
        return new Meeting(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Meeting rename(Name name) {
        return new Meeting(name, null);
    }
}
