/*
 * This file is generated by jOOQ.
 */
package me.tj3828.jooq;


import me.tj3828.jooq.tables.Meeting;
import me.tj3828.jooq.tables.Person;
import me.tj3828.jooq.tables.records.MeetingRecord;
import me.tj3828.jooq.tables.records.PersonRecord;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MeetingRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
    public static final UniqueKey<PersonRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;
    public static final UniqueKey<PersonRecord> UK_585QCYC8QH7BG1FWGM1PJ4FUS = UniqueKeys0.UK_585QCYC8QH7BG1FWGM1PJ4FUS;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<MeetingRecord> CONSTRAINT_6 = Internal.createUniqueKey(Meeting.MEETING, "CONSTRAINT_6", Meeting.MEETING.ID);
        public static final UniqueKey<PersonRecord> CONSTRAINT_8 = Internal.createUniqueKey(Person.PERSON, "CONSTRAINT_8", Person.PERSON.ID);
        public static final UniqueKey<PersonRecord> UK_585QCYC8QH7BG1FWGM1PJ4FUS = Internal.createUniqueKey(Person.PERSON, "UK_585QCYC8QH7BG1FWGM1PJ4FUS", Person.PERSON.EMAIL);
    }
}
