/*
 * This file is generated by jOOQ.
 */
package me.tj3828.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.HIBERNATE_SEQUENCE</code>
     */
    public static final Sequence<Long> HIBERNATE_SEQUENCE = new SequenceImpl<Long>("HIBERNATE_SEQUENCE", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
