/*
 * This file is generated by jOOQ.
 */
package me.tj3828.jooq;


import me.tj3828.jooq.tables.Meeting;
import me.tj3828.jooq.tables.Person;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.MEETING</code>.
     */
    public static final Meeting MEETING = me.tj3828.jooq.tables.Meeting.MEETING;

    /**
     * The table <code>PUBLIC.PERSON</code>.
     */
    public static final Person PERSON = me.tj3828.jooq.tables.Person.PERSON;
}
